name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - deploy-test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip artifacts
        run: zip -r site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-handyapp-web-test"
          slot-name: "Production"
          package: "site.zip"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2700E678D1B34F6B910E3D054DF3AD1F }}
