name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - run: npm ci
      - run: npm run build

      - uses: azure/webapps-deploy@v3
        with:
          app-name: dev-handyapp-web-test
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: dist
